include:
  - board: corneish_zen_left//zmk
    # snippet: zmk-usb-logging  # uncomment to enable logging
  - board: corneish_zen_right//zmk
  - board: corneish_zen_left//zmk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_left_with_studio
